import type { AssetCategory, AssetStatus } from '@/types/database'

// ─── Standards per category ───────────────────────────────────

export const CATEGORY_STANDARDS: Partial<Record<AssetCategory, string[]>> = {
  APS:  ['AS/NZS 1891.4:2009', 'AS 1657-2018'],
  ST:   ['AS/NZS 1891.1:2007', 'AS/NZS 1891.4:2009'],
  TMAP: ['AS/NZS 1891.4:2009', 'AS/NZS 1891.1:2007'],
  CAP:  ['AS/NZS 1891.4:2009', 'AS/NZS 1891.1:2007'],
  HSL:  ['AS/NZS 1891.4:2009', 'AS/NZS 1891.2:2001'],
  VSL:  ['AS/NZS 1891.4:2009', 'AS/NZS 1891.2:2001'],
  LD:   ['AS 1657-2018', 'AS/NZS 1891.4:2009'],
  GR:   ['AS 1657-2018', 'AS/NZS 4994.1:2009'],
  WW:   ['AS 1657-2018'],
  STP:  ['AS 1657-2018'],
  STR:  ['AS 1657-2018'],
  SL:   ['AS 1657-2018', 'AS/NZS 1891.4:2009'],
  EK:   ['AS 1657-2018'],
  PL:   ['AS 1657-2018'],
  GHK:  ['AS 1657-2018'],
  SS:   ['AS 1319-1994', 'AS/NZS 1891.4:2009'],
  DB:   ['AS/NZS 1891.4:2009', 'AS 5532-2013'],
  RR:   ['AS/NZS 1891.4:2009', 'EN 795'],
  SPM:  ['AS/NZS 4600:2018', 'AS 1657-2018'],
  OSE:  ['AS/NZS 1891.4:2009'],
  R:    ['AS/NZS 1891.4:2009', 'AS 1657-2018'],
}

export const DEFAULT_STANDARD = 'AS/NZS 1891.4:2009'

export function getDefaultStandard(category: AssetCategory): string {
  return CATEGORY_STANDARDS[category]?.[0] ?? DEFAULT_STANDARD
}

// ─── Quick-fill finding options per category + status ─────────
// Each entry is a complete Finding+CorrectiveAction pair

export interface QuickFillOption {
  label: string
  finding: string
  corrective_action: string
  status: AssetStatus
  priority: 1 | 2 | 3 | null
}

export const QUICK_FILL_OPTIONS: Partial<Record<AssetCategory, QuickFillOption[]>> = {
  APS: [
    { label: 'Compliant — signage present & legible', status: 'compliant', priority: null,
      finding: 'Access point signage is present, clearly visible, and in good condition. Signage correctly identifies the hazard area and required PPE.',
      corrective_action: '' },
    { label: 'Missing signage', status: 'non_compliant', priority: 2,
      finding: 'No access point signage is present at this location.',
      corrective_action: 'Install compliant access point signage indicating fall hazard and PPE requirements per AS/NZS 1891.4:2009 Cl. 9.2.' },
    { label: 'Faded / illegible', status: 'non_compliant', priority: 2,
      finding: 'Existing signage is significantly faded and illegible.',
      corrective_action: 'Replace signage with new compliant signage. Ensure text and symbols are clearly visible at the required viewing distance.' },
    { label: 'Recommend replacement', status: 'recommendation', priority: 3,
      finding: 'Signage is functional but showing signs of weathering.',
      corrective_action: 'Plan replacement of access point signage at next scheduled maintenance.' },
  ],
  ST: [
    { label: 'Compliant — strop in good condition', status: 'compliant', priority: null,
      finding: 'Strop is in good condition with no visible damage to webbing, stitching, or hardware. Labels are legible and within service life.',
      corrective_action: '' },
    { label: 'Webbing damage', status: 'non_compliant', priority: 1,
      finding: 'Strop webbing shows signs of cuts, abrasion, or UV degradation beyond acceptable limits.',
      corrective_action: 'Remove strop from service immediately. Replace with new AS/NZS 1891.1 compliant strop. Do not use until replacement is installed.' },
    { label: 'Hardware corrosion', status: 'non_compliant', priority: 1,
      finding: 'Carabiner/snap hook hardware shows significant corrosion affecting function.',
      corrective_action: 'Remove from service. Replace with new compliant hardware. Inspect and clean anchor points.' },
    { label: 'Label illegible', status: 'non_compliant', priority: 2,
      finding: 'Manufacturer label is illegible — service life and load rating cannot be verified.',
      corrective_action: 'Remove from service. Replace with new tagged strop.' },
    { label: 'Approaching end of service life', status: 'recommendation', priority: 3,
      finding: 'Strop is functional but approaching the recommended 10-year maximum service life.',
      corrective_action: 'Plan replacement within 12 months. Monitor condition at each use.' },
  ],
  TMAP: [
    { label: 'Compliant — anchor secure & tagged', status: 'compliant', priority: null,
      finding: 'Anchor point is structurally sound with no signs of corrosion, damage, or movement. Base plate is secure and correctly sealed. Load indicator/certification tag is present and current.',
      corrective_action: '' },
    { label: 'Anchor movement detected', status: 'non_compliant', priority: 1,
      finding: 'Anchor point exhibits movement when load-tested. Base plate is not secure.',
      corrective_action: 'Remove from service immediately. Re-engineer anchor point fixing per AS/NZS 1891.4:2009. Do not use for fall arrest until rectified and re-tested.' },
    { label: 'Significant corrosion', status: 'non_compliant', priority: 1,
      finding: 'Anchor point and/or base plate show significant corrosion compromising structural integrity.',
      corrective_action: 'Remove from service. Replace with new compliant anchor point. Investigate cause of corrosion and treat substrate.' },
    { label: 'Sealant failure', status: 'non_compliant', priority: 2,
      finding: 'Sealant around base plate has failed, creating potential for water ingress and corrosion.',
      corrective_action: 'Remove old sealant, clean, and apply new approved sealant around base plate perimeter. Re-inspect in 6 months.' },
    { label: 'Certification tag missing', status: 'non_compliant', priority: 2,
      finding: 'Certification/identification tag is missing from anchor point.',
      corrective_action: 'Identify anchor point from installation records. Install new ID tag with next recertification date.' },
    { label: 'Surface corrosion only', status: 'recommendation', priority: 3,
      finding: 'Minor surface corrosion noted on anchor hardware. Structural integrity appears maintained.',
      corrective_action: 'Clean, treat with rust converter, and apply protective coating. Monitor at next annual inspection.' },
    { label: 'Sealant weathering', status: 'recommendation', priority: 3,
      finding: 'Base plate sealant showing signs of weathering. Recommend resealing within 12 months.',
      corrective_action: 'Reseal base plate at next maintenance visit.' },
  ],
  CAP: [
    { label: 'Compliant — anchor secure', status: 'compliant', priority: null,
      finding: 'Concrete anchor point is secure with no movement, surface corrosion is minimal, and surrounding concrete substrate shows no cracking or spalling.',
      corrective_action: '' },
    { label: 'Anchor movement', status: 'non_compliant', priority: 1,
      finding: 'Concrete anchor exhibits movement under test. Fixing integrity compromised.',
      corrective_action: 'Remove from service immediately. Inspect concrete substrate. Re-core, re-anchor, and re-test to design load.' },
    { label: 'Concrete spalling around anchor', status: 'non_compliant', priority: 1,
      finding: 'Spalling and cracking of concrete substrate around anchor point reduces fixing confidence.',
      corrective_action: 'Engage structural engineer to assess. Repair substrate and re-test anchor point before returning to service.' },
    { label: 'Corrosion at fixing', status: 'non_compliant', priority: 2,
      finding: 'Significant corrosion at stud/bolt — may compromise rated load.',
      corrective_action: 'Replace anchor. Re-test to manufacturer specified proof load.' },
    { label: 'Minor cracking nearby', status: 'recommendation', priority: 3,
      finding: 'Minor hairline cracking in concrete near anchor. Does not appear to affect fixing.',
      corrective_action: 'Monitor and re-inspect at next annual recertification. Seal cracks with appropriate compound.' },
  ],
  HSL: [
    { label: 'Compliant — system serviceable', status: 'compliant', priority: null,
      finding: 'Static line system is in good condition. Wire rope is free of kinks, corrosion, and broken strands. End terminations, tensioner, and intermediate supports are all secure and functional.',
      corrective_action: '' },
    { label: 'Broken wire strands', status: 'non_compliant', priority: 1,
      finding: 'Wire rope has broken strands detected — system cannot be rated for fall arrest.',
      corrective_action: 'Remove from service immediately. Replace wire rope with new compliant rope. Re-tension per manufacturer specifications and re-test.' },
    { label: 'End termination failure', status: 'non_compliant', priority: 1,
      finding: 'End termination/swaged fitting shows signs of loosening or damage.',
      corrective_action: 'Remove system from service. Replace end termination with new certified fitting. Re-test to rated load.' },
    { label: 'Inadequate tension / excessive sag', status: 'non_compliant', priority: 2,
      finding: 'Wire rope tension below minimum requirement — excessive sag noted.',
      corrective_action: 'Re-tension wire rope per manufacturer specifications. Verify intermediate support spacing is within limits.' },
    { label: 'Intermediate support loose', status: 'non_compliant', priority: 2,
      finding: 'One or more intermediate support stanchions are loose or showing base plate movement.',
      corrective_action: 'Secure or replace affected intermediate supports. Re-check wire rope tension after repair.' },
    { label: 'Surface corrosion on rope', status: 'recommendation', priority: 3,
      finding: 'Light surface corrosion on wire rope. No broken strands detected. Tension adequate.',
      corrective_action: 'Clean wire rope and apply corrosion inhibitor. Re-inspect at next annual certification.' },
  ],
  VSL: [
    { label: 'Compliant — VSL serviceable', status: 'compliant', priority: null,
      finding: 'Vertical static line is in good condition. Wire rope free of damage. Top and bottom terminations secure. Travel restraint device operates correctly.',
      corrective_action: '' },
    { label: 'Rope damage', status: 'non_compliant', priority: 1,
      finding: 'Vertical wire rope shows kinks, bird-caging, or broken strands.',
      corrective_action: 'Remove from service. Replace rope and re-terminate. Do not use for vertical access until repaired.' },
    { label: 'Top anchor insecure', status: 'non_compliant', priority: 1,
      finding: 'Top anchor fixing for vertical static line shows movement.',
      corrective_action: 'Remove from service. Re-engineer top anchor fixing per AS/NZS 1891.4:2009.' },
    { label: 'Travel device malfunction', status: 'non_compliant', priority: 1,
      finding: 'Fall arrest travel device does not lock correctly during simulated fall test.',
      corrective_action: 'Remove device from service. Replace with new compliant travel device.' },
  ],
  LD: [
    { label: 'Compliant — ladder serviceable', status: 'compliant', priority: null,
      finding: 'Ladder is in good structural condition. Rungs, stiles, and fixings are sound. Safety cage (where fitted) is complete and secure.',
      corrective_action: '' },
    { label: 'Rung damage / missing', status: 'non_compliant', priority: 1,
      finding: 'One or more rungs are cracked, bent, or missing — ladder is unsafe for use.',
      corrective_action: 'Barricade ladder from use immediately. Repair or replace damaged rungs per AS 1657-2018. Re-inspect before returning to service.' },
    { label: 'Fixing looseness', status: 'non_compliant', priority: 1,
      finding: 'Ladder wall fixings are loose — lateral stability is insufficient.',
      corrective_action: 'Re-fix ladder to structure at all required fixing points per AS 1657-2018 Cl. 4.6.' },
    { label: 'Safety cage damaged', status: 'non_compliant', priority: 2,
      finding: 'Safety cage hoops are bent or partially missing, reducing fall protection.',
      corrective_action: 'Repair or replace cage sections. Verify cage complies with AS 1657-2018 for hoop spacing.' },
    { label: 'Surface corrosion', status: 'recommendation', priority: 3,
      finding: 'Ladder shows surface corrosion but structural integrity appears maintained.',
      corrective_action: 'Clean, treat, and repaint affected areas. Monitor at next inspection.' },
  ],
  GR: [
    { label: 'Compliant — guardrail serviceable', status: 'compliant', priority: null,
      finding: 'Guardrail is in good condition, properly secured, and at the correct height. Top rail, mid rail, and kick board (where required) are all present and undamaged.',
      corrective_action: '' },
    { label: 'Top rail below minimum height', status: 'non_compliant', priority: 1,
      finding: 'Guardrail top rail height is below the minimum 1000mm required by AS 1657-2018.',
      corrective_action: 'Replace or modify guardrail to achieve minimum 1000mm top rail height per AS 1657-2018 Cl. 3.4.2.' },
    { label: 'Post base loose', status: 'non_compliant', priority: 1,
      finding: 'Guardrail post base plate is loose — system does not resist required horizontal load.',
      corrective_action: 'Re-fix post base to structure. Verify fixing achieves design load per AS 1657-2018.' },
    { label: 'Mid-rail missing', status: 'non_compliant', priority: 2,
      finding: 'Mid-rail is absent — gap between top rail and walking surface exceeds 500mm.',
      corrective_action: 'Install mid-rail at a height that ensures no gap exceeds 500mm per AS 1657-2018 Cl. 3.4.' },
    { label: 'Significant corrosion', status: 'non_compliant', priority: 2,
      finding: 'Guardrail shows significant corrosion affecting structural cross-section.',
      corrective_action: 'Assess structural adequacy. Replace affected sections and apply corrosion-resistant finish.' },
    { label: 'Surface corrosion only', status: 'recommendation', priority: 3,
      finding: 'Surface corrosion present. Structural integrity maintained.',
      corrective_action: 'Clean, treat, and re-coat affected sections at next maintenance.' },
  ],
  WW: [
    { label: 'Compliant — walkway serviceable', status: 'compliant', priority: null,
      finding: 'Walkway is in good condition with non-slip surface intact, all fixings secure, and guardrails compliant.',
      corrective_action: '' },
    { label: 'Non-slip surface worn', status: 'non_compliant', priority: 2,
      finding: 'Anti-slip surface treatment is worn and no longer effective — slip hazard exists.',
      corrective_action: 'Apply new non-slip treatment per AS 1657-2018 Cl. 3.3.3.' },
    { label: 'Panel loose / missing fixings', status: 'non_compliant', priority: 2,
      finding: 'Walkway panels are loose or have missing fixings — movement under foot loading.',
      corrective_action: 'Re-fix all loose panels and replace missing fixings.' },
  ],
  STP: [
    { label: 'Compliant', status: 'compliant', priority: null,
      finding: 'Step is in good condition, securely fixed, with non-slip tread surface in good condition.',
      corrective_action: '' },
    { label: 'Step loose', status: 'non_compliant', priority: 1,
      finding: 'Step is not securely fixed and moves under foot loading.',
      corrective_action: 'Re-fix step to structure. Verify fixings achieve design load per AS 1657-2018.' },
    { label: 'Non-slip worn', status: 'non_compliant', priority: 2,
      finding: 'Non-slip tread nosing is worn or missing.',
      corrective_action: 'Replace tread nosing with compliant anti-slip insert or coating.' },
  ],
  STR: [
    { label: 'Compliant', status: 'compliant', priority: null,
      finding: 'Stair structure is in good condition. Treads, handrails, and fixings are all secure. Non-slip treatment is effective.',
      corrective_action: '' },
    { label: 'Handrail loose', status: 'non_compliant', priority: 1,
      finding: 'Stair handrail is loose — does not meet required lateral load resistance.',
      corrective_action: 'Re-fix handrail posts and rail. Verify resistance to 450N lateral load per AS 1657-2018.' },
    { label: 'Non-slip treads worn', status: 'non_compliant', priority: 2,
      finding: 'Non-slip tread nosings are worn or missing on multiple treads.',
      corrective_action: 'Replace all worn nosings with compliant anti-slip inserts.' },
  ],
  SL: [
    { label: 'Compliant', status: 'compliant', priority: null,
      finding: 'Step ladder crossover system is in good condition. All treads, handrails, and structural members are secure and undamaged.',
      corrective_action: '' },
    { label: 'Handrail missing', status: 'non_compliant', priority: 1,
      finding: 'Handrail is absent from one or both sides of the step ladder.',
      corrective_action: 'Install compliant handrail on both sides per AS 1657-2018.' },
  ],
  EK: [
    { label: 'Compliant — gate self-closes correctly', status: 'compliant', priority: null,
      finding: 'Guardrail entry kit is in good condition. Self-closing mechanism operates correctly. Gate latches securely and does not open inward over the fall hazard.',
      corrective_action: '' },
    { label: 'Self-close mechanism failed', status: 'non_compliant', priority: 1,
      finding: 'Gate does not self-close — remains open after release, leaving fall hazard unguarded.',
      corrective_action: 'Repair or replace self-closing mechanism. Gate must close and latch without manual intervention per AS 1657-2018.' },
    { label: 'Gate opens inward', status: 'non_compliant', priority: 1,
      finding: 'Gate opens inward over the fall hazard — non-compliant.',
      corrective_action: 'Reconfigure gate to open away from the fall hazard per AS 1657-2018 Cl. 3.5.' },
    { label: 'Latch worn', status: 'non_compliant', priority: 2,
      finding: 'Gate latch is worn and does not engage reliably.',
      corrective_action: 'Replace latch assembly with new compliant unit.' },
  ],
  PL: [
    { label: 'Compliant', status: 'compliant', priority: null,
      finding: 'Platform is in good structural condition. Guardrails, toe-boards, and non-slip flooring are compliant.',
      corrective_action: '' },
    { label: 'Flooring damage', status: 'non_compliant', priority: 1,
      finding: 'Platform flooring has holes or deformation creating a trip or fall hazard.',
      corrective_action: 'Replace damaged flooring sections with compliant non-slip panels per AS 1657-2018.' },
    { label: 'Guardrail non-compliant', status: 'non_compliant', priority: 1,
      finding: 'Platform guardrail does not meet minimum height or mid-rail requirements.',
      corrective_action: 'Modify or replace guardrail to comply with AS 1657-2018 Cl. 3.4.' },
  ],
  GHK: [
    { label: 'Compliant — hatch self-closes', status: 'compliant', priority: null,
      finding: 'Guardrail hatch kit is in good condition. Hatch operates correctly and self-closes. Guardrail integrity maintained when closed.',
      corrective_action: '' },
    { label: 'Hatch does not self-close', status: 'non_compliant', priority: 1,
      finding: 'Hatch does not self-close — fall hazard left unguarded when operator passes through.',
      corrective_action: 'Repair or replace spring/counterbalance mechanism. Hatch must self-close per AS 1657-2018.' },
    { label: 'Gap in guardrail when closed', status: 'non_compliant', priority: 1,
      finding: 'When hatch is closed, gap in guardrail system exceeds allowable.',
      corrective_action: 'Adjust or replace hatch to eliminate gap. Guardrail integrity must be maintained when hatch is closed.' },
  ],
  SS: [
    { label: 'Compliant — signage present', status: 'compliant', priority: null,
      finding: 'Safety signage is present, clearly visible, in good condition, and correctly communicates the required safety message.',
      corrective_action: '' },
    { label: 'Missing signage', status: 'non_compliant', priority: 2,
      finding: 'Required safety signage is absent from this location.',
      corrective_action: 'Install compliant safety signage per AS 1319-1994 and AS/NZS 1891.4:2009 requirements.' },
    { label: 'Faded / damaged', status: 'non_compliant', priority: 3,
      finding: 'Existing safety signage is faded, damaged, or illegible.',
      corrective_action: 'Replace with new compliant signage.' },
  ],
  DB: [
    { label: 'Compliant — davit base secure', status: 'compliant', priority: null,
      finding: 'Davit base is in good condition, securely fixed to substrate, and free from significant corrosion. Receiver socket is clean and locking mechanism operates correctly.',
      corrective_action: '' },
    { label: 'Base movement under load', status: 'non_compliant', priority: 1,
      finding: 'Davit base exhibits movement under load test — fixing integrity is compromised.',
      corrective_action: 'Remove from service immediately. Re-engineer base fixing to achieve rated design load. Do not use until re-tested and certified.' },
    { label: 'Significant corrosion', status: 'non_compliant', priority: 1,
      finding: 'Significant corrosion on davit base socket or base plate affecting structural integrity.',
      corrective_action: 'Remove from service. Replace with new compliant base unit. Treat substrate before re-installation.' },
    { label: 'Locking pin missing', status: 'non_compliant', priority: 2,
      finding: 'Locking pin/locking mechanism for the davit arm is missing.',
      corrective_action: 'Source and install correct locking pin from manufacturer. Do not use davit without correct locking mechanism.' },
    { label: 'Socket debris', status: 'recommendation', priority: 3,
      finding: 'Debris in receiver socket may impede correct davit arm seating.',
      corrective_action: 'Clean socket. Verify davit arm seats fully and locks correctly.' },
  ],
  RR: [
    { label: 'Compliant — rail system operational', status: 'compliant', priority: null,
      finding: 'Rigid rail system is in good condition. Rail sections are straight and securely fixed. Trolley moves freely and arrest function is operational.',
      corrective_action: '' },
    { label: 'Rail section damage', status: 'non_compliant', priority: 1,
      finding: 'Rail section is bent, cracked, or has gaps affecting trolley travel.',
      corrective_action: 'Remove from service. Replace damaged rail sections. Re-test system per manufacturer requirements.' },
    { label: 'Trolley does not arrest', status: 'non_compliant', priority: 1,
      finding: 'Fall arrest trolley does not lock during simulated fall test.',
      corrective_action: 'Remove trolley from service. Replace with certified unit. Re-test before return to service.' },
    { label: 'Support fixing loose', status: 'non_compliant', priority: 2,
      finding: 'One or more rail support brackets are loose.',
      corrective_action: 'Re-fix all loose brackets. Verify fixings achieve design load per system specification.' },
  ],
  SPM: [
    { label: 'Compliant — mesh intact', status: 'compliant', priority: null,
      finding: 'Skylight protection mesh is in good condition, securely fixed around the full perimeter, with no tears, holes, or gaps.',
      corrective_action: '' },
    { label: 'Mesh tear or hole', status: 'non_compliant', priority: 1,
      finding: 'Protection mesh has tear or hole — does not provide full fall protection over skylight.',
      corrective_action: 'Remove from service immediately. Replace mesh with new compliant fall-rated mesh. Do not allow access near this skylight until repaired.' },
    { label: 'Fixing failure', status: 'non_compliant', priority: 1,
      finding: 'Mesh fixing points have failed — mesh is partially detached from the skylight frame.',
      corrective_action: 'Immediately re-secure or replace mesh. Verify all fixing points achieve required holding strength.' },
    { label: 'Mesh sagging', status: 'non_compliant', priority: 2,
      finding: 'Mesh has significant sag that may not arrest a fall before the worker contacts the skylight.',
      corrective_action: 'Re-tension or replace mesh. Ensure sag does not exceed one-third of the shortest span.' },
    { label: 'Minor corrosion to frame', status: 'recommendation', priority: 3,
      finding: 'Skylight frame shows minor corrosion at mesh fixing points.',
      corrective_action: 'Treat and re-coat corroded areas. Monitor at next inspection.' },
  ],
  OSE: [
    { label: 'Compliant', status: 'compliant', priority: null,
      finding: 'Safety equipment is in good condition, correctly installed, and functional. Labels are legible and within service life.',
      corrective_action: '' },
    { label: 'Equipment damaged', status: 'non_compliant', priority: 2,
      finding: 'Equipment is visibly damaged and requires assessment before further use.',
      corrective_action: 'Remove from service. Assess and repair or replace as required.' },
    { label: 'Service life expired', status: 'non_compliant', priority: 2,
      finding: 'Equipment has reached or exceeded its rated service life.',
      corrective_action: 'Remove from service immediately. Replace with new equipment.' },
  ],
  R: [
    { label: 'Additional anchor points recommended', status: 'recommendation', priority: 3,
      finding: 'Additional anchor points are recommended to improve coverage and reduce re-rigging during work tasks.',
      corrective_action: 'Engage Abseal to design and install additional anchor points to improve fall protection coverage.' },
    { label: 'Rescue plan required', status: 'recommendation', priority: 2,
      finding: 'No documented fall arrest rescue plan is in place for this height safety system.',
      corrective_action: 'Develop and implement a documented rescue plan. Train all system users in rescue procedures.' },
    { label: 'Height safety audit recommended', status: 'recommendation', priority: 3,
      finding: 'A full height safety audit is recommended to assess all roof access requirements.',
      corrective_action: 'Commission a comprehensive height safety audit of the site.' },
  ],
}

// ─── Inspection checklist per category ───────────────────────

export const INSPECTION_CHECKLIST: Partial<Record<AssetCategory, string[]>> = {
  TMAP: ['No movement under test load', 'No structural corrosion to base plate or shaft', 'Sealant intact around base plate', 'Load indicator / ID tag present', 'Connecting point free of damage'],
  CAP:  ['No movement under test load', 'Concrete substrate free of spalling/cracking', 'No significant corrosion to stud', 'Eye / connecting point undamaged'],
  HSL:  ['Wire rope free of kinks/corrosion/broken strands', 'End terminations secure', 'Correct rope tension', 'All intermediate supports secure', 'Energy absorber checked', 'ID tag / certification current'],
  VSL:  ['No rope damage or deformation', 'Top anchor secure', 'Bottom tensioner functional', 'Travel device locks correctly'],
  LD:   ['All rungs present and undamaged', 'Stiles straight and undamaged', 'All fixings tight', 'Safety cage present and complete', 'Top access landing compliant'],
  GR:   ['Top rail ≥ 1000mm from walking surface', 'Mid-rail present (max 500mm gap)', 'Kick board present where required', 'All post bases secure', 'No significant corrosion'],
  EK:   ['Self-closing mechanism functions', 'Gate latches securely', 'Opens away from fall hazard', 'Hardware undamaged'],
  DB:   ['No movement under test load', 'No significant corrosion', 'Locking pin present and functional', 'Socket clean and undamaged', 'Certification plate present'],
  SPM:  ['Mesh fully covers skylight', 'No tears, holes, or cuts in mesh', 'All perimeter fixings secure', 'Sag within permitted limits'],
}

// ─── Priority config ──────────────────────────────────────────

export const PRIORITY_CONFIG = {
  1: {
    label: 'Priority 1',
    sub:   'Immediate action required',
    color: 'text-status-noncompliant',
    bg:    'bg-status-noncompliant-bg',
    border:'border-status-noncompliant/40',
    dot:   'bg-status-noncompliant',
  },
  2: {
    label: 'Priority 2',
    sub:   'Action within 30 days',
    color: 'text-status-recommendation',
    bg:    'bg-status-recommendation-bg',
    border:'border-status-recommendation/40',
    dot:   'bg-status-recommendation',
  },
  3: {
    label: 'Priority 3',
    sub:   'Planned maintenance',
    color: 'text-yellow-500',
    bg:    'bg-yellow-500/10',
    border:'border-yellow-500/30',
    dot:   'bg-yellow-500',
  },
} as const

// ─── Status config ────────────────────────────────────────────

export const ASSET_STATUS_CONFIG = {
  compliant: {
    label:  'Compliant',
    color:  'text-status-compliant',
    bg:     'bg-status-compliant-bg',
    border: 'border-status-compliant/40',
    dot:    'bg-status-compliant',
    ring:   'ring-status-compliant/30',
  },
  non_compliant: {
    label:  'Non-Compliant',
    color:  'text-status-noncompliant',
    bg:     'bg-status-noncompliant-bg',
    border: 'border-status-noncompliant/40',
    dot:    'bg-status-noncompliant',
    ring:   'ring-status-noncompliant/30',
  },
  recommendation: {
    label:  'Recommendation',
    color:  'text-status-recommendation',
    bg:     'bg-status-recommendation-bg',
    border: 'border-status-recommendation/40',
    dot:    'bg-status-recommendation',
    ring:   'ring-status-recommendation/30',
  },
  'n/a': {
    label:  'N/A',
    color:  'text-status-na',
    bg:     'bg-status-na-bg',
    border: 'border-status-na/40',
    dot:    'bg-status-na',
    ring:   'ring-status-na/30',
  },
} as const

// ─── Legacy aliases (keep existing imports working) ──────────

export const COMMON_FINDINGS: Partial<Record<AssetCategory, string[]>> = Object.fromEntries(
  Object.entries(QUICK_FILL_OPTIONS).map(([cat, opts]) => [
    cat,
    opts.map((o) => o.finding).filter(Boolean),
  ])
) as Partial<Record<AssetCategory, string[]>>

export const COMMON_CORRECTIVE_ACTIONS: Partial<Record<AssetCategory, string[]>> = Object.fromEntries(
  Object.entries(QUICK_FILL_OPTIONS).map(([cat, opts]) => [
    cat,
    opts.map((o) => o.corrective_action).filter(Boolean),
  ])
) as Partial<Record<AssetCategory, string[]>>
